# Generated by Django 2.1.1 on 2018-10-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookbor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrecord',
            options={'managed': False},
        ),
    ]
