# Generated by Django 2.1.1 on 2018-09-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('categoryname', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
