# Generated by Django 2.1.1 on 2018-09-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='categoryid',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
