# Generated by Django 2.1.1 on 2018-09-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': False},
        ),
    ]
