# Generated by Django 2.1.1 on 2018-09-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20180912_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'managed': True},
        ),
    ]
