# Generated by Django 2.1.1 on 2018-09-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookcate', models.CharField(max_length=2)),
                ('discription', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'bookcate',
                'managed': False,
            },
        ),
    ]
