# Generated by Django 2.1.1 on 2018-10-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=45)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
