# Generated by Django 2.1.1 on 2018-09-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('boardid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'boards',
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=45)),
                ('age', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=4000)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(db_column='boardid', on_delete=django.db.models.deletion.DO_NOTHING, to='boards.Board')),
                ('createdby', models.ForeignKey(db_column='memberid', on_delete=django.db.models.deletion.DO_NOTHING, to='boards.Members')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
