<<<<<<< HEAD
# Generated by Django 2.1.1 on 2018-09-21 11:03
=======
# Generated by Django 2.1.1 on 2018-09-21 00:53
>>>>>>> Steve 1st commit

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='description',
        ),
    ]
