# Generated by Django 2.1.1 on 2018-10-01 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180925_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='createdby',
            field=models.ForeignKey(db_column='memberid', on_delete=django.db.models.deletion.DO_NOTHING, to='boards.Members'),
        ),
    ]
